### ISSUE TITLE
idempotency ?

### ISSUE THREAD

**Issue by tfuzeau** [commscope-ruckus/RUCKUS_ICX_Ansible#48]
Hello,

I'm testing a very basic playbook on a ICX 7150 C12 runing 8.0.95d and I'm supprized by the fact changed is always to 1:

```yaml
---
- hosts: ruckus
  collections:
   - commscope.icx
  connection: network_cli
  gather_facts: no
  vars:
    ansible_become: true
    ansible_become_method: enable
  tasks:
  - name: enable ethernet port 1/1/12
    icx_interface:
        name: ethernet 1/1/12
        enabled: false
        #description: Added by Ansible
  - name: Add a single ethernet 1/1/12 as access(untagged) port to vlan 20
    commscope.icx.icx_vlan:
      name: test-vlan
      vlan_id: 20
      interfaces:
        name:
          - ethernet 1/1/12
```

Running for the 1st time, config is well applied:
```bash
$ ansible-playbook ruckus.yml -v
Using ansible.cfg as config file

PLAY [ruckus] **********************************************************************************************

TASK [enable ethernet port 1/1/12] *************************************************************************
changed: [Ruckus01] => {"changed": true, "commands": ["interface ethernet 1/1/12", "disable"]}

TASK [Add a single ethernet 1/1/12 as access(untagged) port to vlan 20] ************************************
changed: [Ruckus01] => {"changed": true, "commands": ["vlan 20", "vlan 20 name test-vlan", "untagged ethernet 1/1/12", "exit"], "have": [], "output": ["", "", "Port(s) ethe 1/1/12  are already a member of VLAN 20", ""], "want": [{"associated_interfaces": null, "associated_tagged": null, "delay": 10, "interfaces": {"name": ["ethernet 1/1/12"], "purge": null}, "ip_arp_inspection": null, "ip_dhcp_snooping": null, "name": "test-vlan", "state": "present", "tagged": null, "vlan_id": 20}]}

PLAY RECAP *************************************************************************************************
Ruckus01                   : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

But when I'm running it for a 2nd time, changed is still not null, even if the lines are already in the configuration:
```bash
$ ansible-playbook ruckus.yml -v
Using ansible.cfg as config file

PLAY [ruckus] **********************************************************************************************

TASK [enable ethernet port 1/1/12] *************************************************************************
changed: [Ruckus01] => {"changed": true, "commands": ["interface ethernet 1/1/12", "disable"]}

TASK [Add a single ethernet 1/1/12 as access(untagged) port to vlan 20] ************************************
changed: [Ruckus01] => {"changed": true, "commands": ["vlan 20", "vlan 20 name test-vlan", "untagged ethernet 1/1/12", "exit"], "have": [], "output": ["", "", "Port(s) ethe 1/1/12  are already a member of VLAN 20", ""], "want": [{"associated_interfaces": null, "associated_tagged": null, "delay": 10, "interfaces": {"name": ["ethernet 1/1/12"], "purge": null}, "ip_arp_inspection": null, "ip_dhcp_snooping": null, "name": "test-vlan", "state": "present", "tagged": null, "vlan_id": 20}]}

PLAY RECAP *************************************************************************************************
Ruckus01                   : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Am I the only one with this issue? I would expectan "ok=2 changed=0" after the 2nd run, so we can be sure the switch is configured as expected.

Thank you for your help!

Thomas
